### request 1
@host = http://localhost
@port = 5062
@token = CfDJ8JLO8A5qCt5FqlwROFPzDJPpVvHnpGCw5_WFG8ijT1wbZ-Vyie9YRnWYmilEnM71HfpNZzHx7B7uwHla8-zlsd-EQ_cU9MoMLfYGTnLAPkrqmKgI-naPfEhoMYXofoZw9fnnDCHTnSovkVYuIRpfDma2Vo7dgo6DK8oD0pFuZpFHhX6sI1fynqJtjdCDh5JOQm3iL33yD8HeKDDuIpIkoxWziUvv8Gw0uQhQAqM3RP9LYmXG7zzXxncsIf6lDakuVM1j6H0Upph5PNVJlmUXgIlJvIK1xGnTMCR4kNmCcY4CoDvd85SRgA6BEQ4cAFIuTuTzmJ8UI-QgCku2yVNr7IAPqB6trDsZJ8gWmFxF-avfFNEYX86JGY9Ho5iYvwqb0qigViGmRXhi8UyfDER-aV3KNDaCdt3FfB3N18EK79zzKjlHPvfkEf47xHzeWDVqAQ01-Aeb9XtVzAdYXD0MTK343v3m5Dre9DVCHqUBCt8CxTfjj1SfeDmAW4hG68n53HWe58lhpzCmKsbhgnZgDaey_pWhQ0ANOtNFWrJNngQpWd60DBcO9bRys3Rt7PP1EE2JU9gKiFEMC68EI1I-ytSnXZKp0z5VV4KEdrOTHPao_Ftnz_bFrYMcPZcgu48hvQtZD8lRP58QMN8h6S7sag9oEzfoVPi9I4ZpBcfYPiuVqbVbAXbMeGSlniasW3Ejhg
@ownerToken = CfDJ8JLO8A5qCt5FqlwROFPzDJP-de6c12qpA7PP3gi3jbecw4l2H0jAfiuIrE3Sq5Bf53urEV_JBB1_6-knM5xuEgGhzVk_JyWSMrBAQ3xWO9YpvKgqaOarno90sHNjF1Wm_HghzMbqy5ExkVjcMBtvWAZ3eOlceqS6St7l-D6tSg2aiJDsQT6mQwYNm3Y6n43bbtTaox99cM6cf4-EBdsHBQJmEcraCEzd8B44IQwC0djKluMAjW5DUKbQZNVEbCn34Vcsnpvp1z4lA2F6VTuK6r_Vqtli0E5TVuEY-YuknfiZwN1E-km0KjNVghQzNQw9dfc_kIDbHCdtjhXjRjAwhW8ItdEv2sAMKpN0nPfMAMiqc1l8V0Y95kWXdZyos8RO6rZlIYygXjQE8XQFupkguSm0P7dBFQdxHRzUshCQvmVv7UeONymiaCAnlBu88FknNuQMqTH4gsLvn7JyioxDXeLNDd-ML5jOi7hdVcjqJaN41AicK9H7yyqdC6O3zancuOMhspO2NHU3aIHa2VPqCHBI1cimG8fg6owZVxcBtL5bSm3r3j7Xli65iaS8ejKa1VidawgrjtChlqNHLaLV615ITdzO-9gDpb44lAqa8elqgQhE66oFrCnAysx4R_hcEv0fMdwPVxpSABzfF4mqqt2xlFozmHqQCrKjO2wI0C9ZzCUPeZn14INrTaJR4DW2aXy0yoQNgAK-r5vY-yPFFfsuzH6SzpIvE5fZHFwoZ2A-rMfZDYhiktLZ8VYLnmH-bqScrBbCOpkMgOyT9N1RawkBFnOgOqnuFhMH-0rGNdiTphWs8Xeabni48W6ppblDOfKsb43fnx4bzuzgYkp9yBZG5T57bKz9LLIGTZVGbSTpoWlgg8s1ibQwBuE9Pkx21g
@owner2Token = CfDJ8JLO8A5qCt5FqlwROFPzDJNmQDX7EmE_T655j9Uyqefu8TLtJO90b5Lw_uuhQ65Kl42xd6lcbYXh5t9_RlV_KurNMvfPOKXGdczM4e9U5Bak1F_u4b74jPYSyBckTtil5nh0aq5c0oWOluQhazcKyoaw4xs46gBJ-Ha3jCbt-W5h38UWrzJggNOxH2DcsexDPC3_d-ofnQ5kui3iSwCrFxsuiIXgHa2rOnDCwxJvpQ_ZjX2i57U7MaE5NWqOWRclj3vexWW4cUEzz5L7VHWoBcd_HW9--BqdcMAAj8O9mUPgc8y3Fd04YGXvlW2wK2s-1KXqY7c0XbZarApJSgXrsrYg_wVic0myDCsAiNqHxddsd7aIbnSwn3Zcfz0m40f1wJXCsSWIVtwR9W6Np4MYJmII2yZkvvAa9uyC-mE79D8DWs45nshBIssocOM43LfZE7JDL75VizAVSuVNDpSkK3-auRwQE4wIEEfNutLpyIJF8NVFNdNLzMmM3XboNJrMhmpT7MB_iiLGNhPoAMswMBz0JuvQN9oy5InyWsOMqOOtriFVZ3MBOVUkGJ17JszA98RV72GiDiBQvE7dcXASN4mF-P37rWdri6l8NEYDPH0rfeCvIx7p802158A4Jr76OKnizS44KhJ64OXVt_Q0K34CYt--xOGGEmaqEHY1eiJHXcomCqj9g4l1YjN8q2lvyjg05zof0J2vaVVcLppJBzo18Wn94cNMIgBsO3DgPAi-3XVHk8uL88AnyCJ_MwSX20di5IwByvPUw43EHOy4urJ4OWMJIFmgBJn-pBBNZuK8
@adminToken = CfDJ8JLO8A5qCt5FqlwROFPzDJPg10An6BqvMqSpT0VZhp50XVj5tvMNFU_177oo1UNY5xGMg_MYkbFcEoiWIr3ghhxVdzam1UUMBjBpcjJdKlX8rpUO4pAx0jdGRWOcmAD7g-0lDkhhi1SZX0gIAFbFwFsUa4UkvBYz7SggMEsV9QrOoKr6k8Y1Y7S8PAIe0ypyTZ1BQGMAHIQ8qL4kc9gaI9FUIJd9hDHSSE1qfQyO1jX8dr935_I_R7DT4w3HCpUvarvgDm_y4lDYMp-y7qOCNmgdxODuXaDF6FSHMmnrF0BUhSK7AFYRRdYVilQiw2Bn027zHGCzhAkIzv8ZfVwOA2xxadXQVgVHtWVjPvf-j8rl6tcTRK9TtM7B2x_d71SsVu2SdXmMJjWqUwoEVUYutKItmdkj6XAwab7K345aCngmTYpuG2t-s4FbrdHt9OM8JMd71Tt2FpJSHzq-musaCsp0m8nOEwpD8j7Byaonj0ifxVruSFCSNwcQ9toCDwHFVnkFZWEyVxNsmgTAWZtoUL06F45CbJmyrBHne4llhfYGn9SIiylyeBxksEUTAeCaasR60oUcR9MeaM3BP_7xYKLQEcznJ8VYcApgMvSbcDzMIqtswAEEgBwYEZSktLzDLVlTYOVHeGU8yDqfPhJ4OClLRK9lEUzR3QAXdzJWN3L47akQr2F4DkuZnM1lbeIZoop1T4ZC06zM6jDbOla2fa1dW3rZdv5f-Kk7Mo4ZKI0Q1gj8VahKtUFVaOLdQIGgubqYcguNtmDcuHNYRb3x53uHCaH1J4-ZOwTj3iFMyGTV
@testUser = CfDJ8JLO8A5qCt5FqlwROFPzDJNrPN2j3JBzqw0zHiCxPQcJG7277m9AINu87t7Otty12NMOFogExergdPoyTsCaSsIb6EIvA3F0opEGxsD4o3KZ45KnOwPG8NSKVQd_46rbe91p6wOS8oGyhK7pk5Ekfgh2YdvOWAMID6_UclC8GM_qWqGeOOmX6EIV5oJ6FwQ_V4U16_BWYx7NTxEu7TmeGuw3nGXf82L26pVhxFl0r5Mu17lgtp2XheJM2wsxQ4sq1yyHe4gckRZJNX2u6lXbQR7iMwQCf3TDRTz9-VoVGQMeaCticiXSo5OJRoqg6WXAMo7Q-CqCAsG_66W1rE_QJIlPkpsifn3hiUR6OR9CtIlodwBmOm1qYg_zwB53cwnTe3y-0ZDto93ekS8NJkdROIpJ0b9aiaVy7IiZML6UafopNeu_ojImYDE-P-OEl4IkB_waOJw0LFwXUzXmP4bjSerUAa368uqs5O49lVIBLAAX15X9C3oBx_VNbXBEfpWJSbAQgZ_FkPayQUPJkel7AXHWrMZPtGMYx1T0EHmvdUAEZcRLsHz23g_jDrxsHGF_vabXOhkdvwJhgVBFQ10JACcY1DNyHzlsThVkgwfWdqtOhXpZJJimZF7Fw_rhgB1S1ggM8SZZb8uU_dYGKBmlAlqov8tgP_PfzntJwJ_OBCv2mSWUwGTiWpBxJ4YpQdsXeDy5SOaKj5XDzcNECfCBWJlzqc37RecM1q0uxc-eAe5hM-FLFmIDaFwoKhFyqS06buEHx2X3beWRGLq6Oiau6Q9HhcsSBaPEW5rraO8Hm0qhz73Z8z_vLAtK2od5EAay1FuDKU9z73JglpGk7DPvtjEo3szMCvgJ7020t87OBWijwP5ZGikzRXmHyKWqVRcVug

GET {{host}}:{{port}}/api/restaurants?searchPhrase=wiz&pageSize=10&pageNumber=1&sortby=Category&SortDirection=Ascending
Authorization: Bearer {{ownerToken}}
###

### request 2 - restaurant exist
GET {{host}}:{{port}}/api/restaurants/7004
Authorization: Bearer {{adminToken}}
###

### request 3 - restaurant not exist
GET {{host}}:{{port}}/api/restaurants/5000
###

### request 4 - create new restaurant
POST {{host}}:{{port}}/api/restaurants
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
    "Name": "New Owner restaurant2",
    "Description": "A culinary experience like no other",
    "Category": "Asian",
    "HasDelivery": true,
    "ContactEmail": "info@fgourmetdelights.com",
    "ContactNumber": "48-123-123-321",
    "City": "Otwock",
    "Street": "Kupiecka",
    "PostalCode": "05-400"
}
###
GET {{host}}:{{port}}/api/restaurants/1002
Authorization: Bearer {{adminToken}}

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{owner2Token}}

{
    "Name": "HardRock Cafee Owner2",
    "Description": "A metal dishes served by goth girl, on fire plates",
    "Category": "Indian",
    "HasDelivery": true,
    "ContactEmail": "hardrock@inferno.com",
    "ContactNumber": "66-456-654-456",
    "PostalCode": "11-111",
    "City": "Warszaw",
    "Street": "Metalowa 11"
}

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
    "Name": "Tasty Bites2!!!!!",
    "Description": "A cozy restaurant serving various sea dishes",
    "Category": "Asian",
    "HasDelivery": true,
    "ContactEmail": "tastybites@asd.com",
    "ContactNumber": "45-456-654-456",
    "PostalCode": "32-111",
    "City": "New Yourk",
    "Street": "123 Main Street"
}

### delete restaurant 
DELETE  {{host}}:{{port}}/api/restaurants/7005
Authorization: Bearer {{ownerToken}}


### update restaurant
PATCH  {{host}}:{{port}}/api/restaurants/7005
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
  "Name": "Cant update by owner",
  "Description": "Spicy dishes of hot dogs",
  "HasDelivery": true
}

### create dish for a given restaurant
POST  {{host}}:{{port}}/api/restaurants/1002/dishes
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese9122",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 29,
    "KiloCalories": 1000
}

### retrieve all dishes for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes
Authorization: Bearer {{ownerToken}}

### retrieve specific dish for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes/1004

###
### delete dishes for a given restaurant
DELETE  {{host}}:{{port}}/api/restaurants/1002/dishes

### register user
POST {{host}}:{{port}}/api/identity/register
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password.12"
}

### login user
POST {{host}}:{{port}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password.12"
}

### update user details (birth, nationality)
PATCH  {{host}}:{{port}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
    "dateofbirth": "2001-01-22",
    "nationality": "French"
}

### register admin user
POST {{host}}:{{port}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password.12"
}

### assgin user role
POST {{host}}:{{port}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "userEmail": "owner2@test.com",
  "roleName": "Owner"
}
### UNassgin user role
DELETE {{host}}:{{port}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "userEmail": "testuser@test.com",
  "roleName": "Admin"
}
###