### request 1
@host = http://localhost
@port = 5062
@token = CfDJ8JLO8A5qCt5FqlwROFPzDJPI_zz_GV10nRKLssidux2sy69UWag-PkfnqmYdujNdhWuk64zJTQJnxat-rBN8QKoiZ75e2DYX3rJEY0qF5WKml1WUT498dDguQwqwKPaXOuPUf_MP9ZKLcLQ_q8NOzI7TT5f-m9hWbiM8mPmS_v92NvRzLneWDQd_wVe9Z7V8MQ9Q0_FTIQ2B9VssQv1JEv1si2N1JH1e3sFnDUtaNwJxg47anbfaknl8VgTra5K3yWMJUXpf2OBqFvmr_PbAzVQbj5fCqGn7TSKV6HFDzd7_TAmeb_cSl-7x3AoOaNoecVpOSKEGnqVHmrBq0Phdgm_C5MQzz3xw6r_zN_s4O8x6fFgT_K0T2jiXQlYudeg8knpiEZrCnKkCd64YBGApIU8wuQRVH8bW9FkRFHexoNWWEDonRV9fIt2xWCwV-xR6DD3g9KIvLREPH5-CdvqI-2G4Ck5SBhy22xN7h25huVs-RIhDQUNq71PVRFl3RlUwWUpQkXgkPIZdrTkcnlb-hibb_8fX8hqvgiMIq0ez9UOCqivGe2CJj6L7dedglwq5BKmigSl_nezAakxfQAogApn2r-JKMR3OzaVpZWdZc1bStQ_BveAvVYwr0X6GlOW0W6_BY89vpVNVJIwqdNDp5BtH1jq37Bil1ad5IUnmC89q028N5Ml5eNjdtOvq19mGSA

GET {{host}}:{{port}}/api/restaurants
#Authorization: Bearer {{token}}
###

### request 2 - restaurant exist
GET {{host}}:{{port}}/api/restaurants/1002
Authorization: Bearer {{token}}
###

### request 3 - restaurant not exist
GET {{host}}:{{port}}/api/restaurants/5000
###

### request 4 - create new restaurant
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json

{
    "Name": "Bar Lan Ankh",
    "Description": "A culinary experience like no other",
    "Category": "Asian",
    "HasDelivery": true,
    "ContactEmail": "info@fgourmetdelights.com",
    "ContactNumber": "48-123-123-321",
    "City": "Otwock",
    "Street": "Kupiecka",
    "PostalCode": "05-400"
}
###
GET {{host}}:{{port}}/api/restaurants/1002

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json

{
    "Name": "HardRock Cafee",
    "Description": "A metal dishes served by goth girl, on fire plates",
    "Category": "Indian",
    "HasDelivery": true,
    "ContactEmail": "hardrock@inferno.com",
    "ContactNumber": "66-456-654-456",
    "PostalCode": "11-111",
    "City": "Warszaw",
    "Street": "Metalowa 11"
}

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json

{
    "Name": "Tasty Bites",
    "Description": "A cozy restaurant serving various sea dishes",
    "Category": "International Cuisine",
    "HasDelivery": true,
    "ContactEmail": "tastybites",
    "ContactNumber": "456-654-456",
    "PostalCode": "323-111",
    "City": "New Yourk",
    "Street": "123 Main Street"
}

### delete restaurant 
DELETE  {{host}}:{{port}}/api/restaurants/2002

### update restaurant
PATCH  {{host}}:{{port}}/api/restaurants/4002
Content-Type: application/json

{
  "Name": "Bar Lan Ankh",
  "Description": "Spicy dishes of hot dogs",
  "HasDelivery": true
}

### create dish for a given restaurant
POST  {{host}}:{{port}}/api/restaurants/1002/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese912",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 29,
    "KiloCalories": 1000
}

### retrieve all dishes for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes

### retrieve specific dish for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes/1004

###
### delete dishes for a given restaurant
DELETE  {{host}}:{{port}}/api/restaurants/1002/dishes

### register user
POST {{host}}:{{port}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password.12"
}

### login user
POST {{host}}:{{port}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password.12"
}

### 