### request 1
@host = http://localhost
@port = 5062
@token = CfDJ8JLO8A5qCt5FqlwROFPzDJPpVvHnpGCw5_WFG8ijT1wbZ-Vyie9YRnWYmilEnM71HfpNZzHx7B7uwHla8-zlsd-EQ_cU9MoMLfYGTnLAPkrqmKgI-naPfEhoMYXofoZw9fnnDCHTnSovkVYuIRpfDma2Vo7dgo6DK8oD0pFuZpFHhX6sI1fynqJtjdCDh5JOQm3iL33yD8HeKDDuIpIkoxWziUvv8Gw0uQhQAqM3RP9LYmXG7zzXxncsIf6lDakuVM1j6H0Upph5PNVJlmUXgIlJvIK1xGnTMCR4kNmCcY4CoDvd85SRgA6BEQ4cAFIuTuTzmJ8UI-QgCku2yVNr7IAPqB6trDsZJ8gWmFxF-avfFNEYX86JGY9Ho5iYvwqb0qigViGmRXhi8UyfDER-aV3KNDaCdt3FfB3N18EK79zzKjlHPvfkEf47xHzeWDVqAQ01-Aeb9XtVzAdYXD0MTK343v3m5Dre9DVCHqUBCt8CxTfjj1SfeDmAW4hG68n53HWe58lhpzCmKsbhgnZgDaey_pWhQ0ANOtNFWrJNngQpWd60DBcO9bRys3Rt7PP1EE2JU9gKiFEMC68EI1I-ytSnXZKp0z5VV4KEdrOTHPao_Ftnz_bFrYMcPZcgu48hvQtZD8lRP58QMN8h6S7sag9oEzfoVPi9I4ZpBcfYPiuVqbVbAXbMeGSlniasW3Ejhg
@ownerToken = CfDJ8JLO8A5qCt5FqlwROFPzDJPdXJo7r1zYR_iuVLRH4OfcoRRZVXnwgoWq3ZVlUpXjmjARzbJoRuOZnx_SQ-uYPg9rFXrdvn1Zxs6XX_9z6HXdFzFMAXYisgrSEIEjH7K1hWDj0LbUUgQY_TuWteVJ2s1GpIMjFV-3RvxJfSajM46i5K9tvGtOcJhLQXa0aG-S8GAX-bkgwCacpM7flUp1-c3ZRj67DKHdxUV8uW5NK142pwOkReXLp0EUHAHk5oGoBxPsITuXVPvA_lI1yX2k-8R3jo09QiIFTU5eABk5SNMBYJj2jgCoYMfLunULXPbdDKxGMJYs55nwGxoQ-bjhtr93Aunyyw9srjbnFRhaaN36p6REme0hb30rzdeeuV5Yuj4jlnQmw2XqOS8JH8WEUft_ApxxjRwH-wL58cNQnDL2I9VkSiqgiGLmLzw0NY19j1ZPswunzccwHPUBGsg1CSEo4SNgW_88ly6DHRlU5BoCpjM9TT10f-d9Z8CRZs8yxCK67qb9cVGL6NaYMXjvMaNUBzmtjudT1eG6Yd5C8u9PdFbt7hlNc4MYyerwTsYmigWji5Csza2bbl_m3fY8bTsKE0gE2uAWw3Gz80Dv_mkaCwKItEqCAKCYQJiBiaVx15DYsAuVqJPqTT9YE6xNFgQAIuecYlLxL6MliNnW7_fXYR7VbMyXCAMYU8nUuCBWSh_ehVZGVVmIiBs3nWefCnRRhwfivx6GDmOwNPZi-sCtA_rqD3617N6JukS5JVVJcwHddqCySVWicmCQjuCIyXyZcYZxttEVPdDn2nb6LlWw
GET {{host}}:{{port}}/api/restaurants
#Authorization: Bearer {{token}}
###

### request 2 - restaurant exist
GET {{host}}:{{port}}/api/restaurants/1002
Authorization: Bearer {{token}}
###

### request 3 - restaurant not exist
GET {{host}}:{{port}}/api/restaurants/5000
###

### request 4 - create new restaurant
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json

{
    "Name": "Bar Lan Ankh",
    "Description": "A culinary experience like no other",
    "Category": "Asian",
    "HasDelivery": true,
    "ContactEmail": "info@fgourmetdelights.com",
    "ContactNumber": "48-123-123-321",
    "City": "Otwock",
    "Street": "Kupiecka",
    "PostalCode": "05-400"
}
###
GET {{host}}:{{port}}/api/restaurants/1002

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json

{
    "Name": "HardRock Cafee",
    "Description": "A metal dishes served by goth girl, on fire plates",
    "Category": "Indian",
    "HasDelivery": true,
    "ContactEmail": "hardrock@inferno.com",
    "ContactNumber": "66-456-654-456",
    "PostalCode": "11-111",
    "City": "Warszaw",
    "Street": "Metalowa 11"
}

### request body validation
POST {{host}}:{{port}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
    "Name": "Tasty Bites2!!!!!",
    "Description": "A cozy restaurant serving various sea dishes",
    "Category": "Asian",
    "HasDelivery": true,
    "ContactEmail": "tastybites@asd.com",
    "ContactNumber": "45-456-654-456",
    "PostalCode": "32-111",
    "City": "New Yourk",
    "Street": "123 Main Street"
}

### delete restaurant 
DELETE  {{host}}:{{port}}/api/restaurants/2002

### update restaurant
PATCH  {{host}}:{{port}}/api/restaurants/4002
Content-Type: application/json

{
  "Name": "Bar Lan Ankh",
  "Description": "Spicy dishes of hot dogs",
  "HasDelivery": true
}

### create dish for a given restaurant
POST  {{host}}:{{port}}/api/restaurants/1002/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese912",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 29,
    "KiloCalories": 1000
}

### retrieve all dishes for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes

### retrieve specific dish for a given restaurant
GET  {{host}}:{{port}}/api/restaurants/1002/dishes/1004

###
### delete dishes for a given restaurant
DELETE  {{host}}:{{port}}/api/restaurants/1002/dishes

### register user
POST {{host}}:{{port}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password.12"
}

### login user
POST {{host}}:{{port}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password.12"
}

### update user details (birth, nationality)
PATCH  {{host}}:{{port}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dateofbirth": "1990-01-22",
    "nationality": "Polish"
}

### register admin user
POST {{host}}:{{port}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password.12"
}